# Generated by Django 3.0.7 on 2020-06-10 10:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('date_create', models.DateTimeField(default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('subject', models.CharField(default='BIO', max_length=10)),
                ('tag', models.CharField(default='BOTANY', max_length=10)),
                ('level', models.CharField(default='EASY', max_length=10)),
                ('creator', models.CharField(default='ADMIN', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Qoptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(default=datetime.datetime.now)),
                ('a', models.CharField(max_length=200)),
                ('b', models.CharField(max_length=200)),
                ('c', models.CharField(max_length=200)),
                ('d', models.CharField(max_length=200)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.Question')),
            ],
        ),
    ]
