# Generated by Django 3.0.7 on 2020-06-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
