# Generated by Django 3.0.8 on 2020-07-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('qn', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Qoptions',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
